name: Test Full Pipeline (extrac_english)

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/test-pipeline.yml'
  pull_request:
    paths:
      - '**.py'
      - 'tests/**'

jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run all tests
        run: pytest tests/

      - name: Run all tests
        run: pytest tests/ --tb=short --disable-warnings
